name: Deploy Application Heroku
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    environment:
      name: MyMusic Application
      url: https://mymusic-application.herokuapp.com/mymusic/swagger-ui/index.html

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file MyMusic/pom.xml
    
    - uses: actions/checkout@v2
    - name: Release MyMusic API
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "mymusic-application"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "MyMusic"
